### PR TITLE
Added an option to show filenames in svg graph

### PR DESCRIPTION
**Pull request by fingerartur**
Example of how the result may look like https://jsfiddle.net/fingerartur/0pqrd6st/

Webpack config
```js
module.exports = {
  entry: "./src/index",
  plugins: [
    new CircularDependencyPlugin(
      visualizer(
        {
          exclude: /node_modules/,
          cwd: process.cwd(),
        },
        {
          filepath: path.join(
            __dirname,
            "circular-dependency-visualization.html"
          ),
          labels: true,
        }
      )
    ),
  ],
};
```

graph

### CODE REVIEW

**Comment by sfrieson** [comment]
Hey @fingerartur, thanks for putting up this contribution. I've been wanting to get around to some better UX around finding/inspecting the graph nodes for a while, but haven't gotten around to it. That's partially because I didn't know others were using the library.

I have a couple concerns with your the proposed approach:
- With the solution of showing the file names all the time, it is quite difficult to read most of the filenames. It is also difficult to see the nodes behind the filenames. Can you still click/drag them behind the file names? I believe, at the moment, you can hover over a node and it will show the filename. Would this work for your use case?
- Also, I'm slightly worried about the possibility of an explosion of config values with all of the other things someone might want to add beside `labels`. It might be more worth the effort to find a way to allow supplying a node render function to give people full control. I don't have any technical solution for this yet though.


I'm curious as to what specifically you are trying to solve for because I might already have some ideas about other solutions that we could possibly work on together.

**Comment by Benno007** [comment]
Hi @sfrieson, we've just started using this plugin to help us with our circular dependency issue in our very large app and got to this issue because we weren't sure if the plugin was working. We were clicking on the dots thinking it would show the file that it represented, but we realized it was a title attribute. Even for instance, `circle:hover { fill: red; }` would have given us an indication that something was meant to happen on-hover.

Thank you for the plugin!

**Comment by sfrieson** [comment]
I agree that the visualization in its current state definitely does not have the best user experience and can be improved. I'll try looking into improving it this weekend taking inspiration from what was done here.

**Comment by sfrieson** [comment]
I have been playing around with this a bit and have found some ways to fix some of the concerns that I had. From the comments here it seems that figuring out the filename for any given node is the main concern, and the title prop is not immediately noticed, since you have to hover for a while.

I will merge this in because I really appreciate you taking the time and initiative to work on this. I'll then make some updates to address my concerns, and then publish a new version. FYI, I plan to remove the label config since filenames will be important to everyone using this package.

**Comment by sfrieson** [comment]
[Version 1.1.2 is published](https://www.npmjs.com/package/circular-dependency-plugin-visualizer). Thank you again for you help and input.

**Pull request merged**
